FROM ubuntu:14.04

MAINTAINER Chi-Jui Wu <cjw21@st-andrews.ac.uk>

RUN apt-get update

#RUN apt-get install -y python-dev python-distribute python-pip

#Run pip install -r requirements.txt

#CMD python run.py