
$rootScript = <<SCRIPT
  apt-get update -y
  apt-get install -y software-properties-common python-software-properties
  apt-get install -y curl git build-essential libssl-dev firefox
  apt-get update -y
  apt-get clean -y
SCRIPT

$userScript = <<SCRIPT
  curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash
  echo "source /home/vagrant/.nvm/nvm.sh" >> /home/vagrant/.profile
  source /home/vagrant/.profile
  nvm install 0.10
  nvm alias default 0.10
  echo "nvm: $(nvm --version)"
  echo "node: $(node --version)"
  echo "npm: $(npm --version)"
  npm install -g npm@next
  npm install -g gulp
SCRIPT

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "nodejs010.box"

  config.vm.provider "virtualbox" do |v|
    # more cpu and memory
    v.memory = 4098
    v.cpus = 2

    # Allow the creation of symlinks for nvm
    # http://blog.liip.ch/archive/2012/07/25/vagrant-and-node-js-quick-tip.html
    vb.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/vagrant","1"]
  end

  # Removes "stdin: is not a tty" annoyance as per
  # https://github.com/SocialGeeks/vagrant-openstack/commit/d3ea0695e64ea2e905a67c1b7e12d794a1a29b97
  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"

  # Shell provisioning.
  config.vm.provision "shell", inline: $rootScript
  config.vm.provision "shell", inline: $userScript, privileged: false

end
