
$rootScript = <<SCRIPT
  cd /home/vagrant
  apt-get update -y
  apt-get install -y software-properties-common python-software-properties
  apt-get install -y git build-essential python2.7 python2.7-dev python-pip python-virtualenv
  
  apt-get update -y
  apt-get install -y 

SCRIPT

$userScript = <<SCRIPT
  cd /home/vagrant
  git clone https://github.com/cjw-charleswu/Recompute -b master
  cd Recompute/
  virtualenv venv
  source venv/bin/activate
  pip install -r requirements.txt
  cd tests/ 
chmod a+x server.sh 
./server.sh
SCRIPT

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "recompute2.box"

  config.vm.provider "virtualbox" do |v|
    # more cpu and memory
    v.memory = 4098
    v.cpus = 2
  end

  # Removes "stdin: is not a tty" annoyance as per
  # https://github.com/SocialGeeks/vagrant-openstack/commit/d3ea0695e64ea2e905a67c1b7e12d794a1a29b97
  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"

  # Shell provisioning.
  config.vm.provision "shell", inline: $rootScript
  config.vm.provision "shell", inline: $userScript, privileged: false

end
