
$rootScript = <<SCRIPT
  apt-get update -y
  apt-get install -y software-properties-common python-software-properties
  apt-get install -y git build-essential python<LANGUAGE_VERSION> python<LANGUAGE_VERSION>-dev python-pip python-virtualenv
  apt-get update -y
SCRIPT

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "python27.box"

  config.vm.provider "virtualbox" do |v|
    # more cpu and memory
    v.memory = <MEMORY>
    v.cpus = <CPUS>
  end

  # Removes "stdin: is not a tty" annoyance as per
  # https://github.com/SocialGeeks/vagrant-openstack/commit/d3ea0695e64ea2e905a67c1b7e12d794a1a29b97
  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"

  # Shell provisioning.
  config.vm.provision "shell", inline: $rootScript

end
