UBUNTU_TRUSTY64 = "ubuntu/trusty64"
UBUNTU_TRUSTY32 = "ubuntu/trusty32"
HASHICORP_PRECISE64 = "hashicorp/precise64"
HASHICORP_PRECISE32 = "hashicorp/precise32"

RECOMPUTE_BOXES = [
    (UBUNTU_TRUSTY64, UBUNTU_TRUSTY64),
    (UBUNTU_TRUSTY32, UBUNTU_TRUSTY32),
    (HASHICORP_PRECISE64, HASHICORP_PRECISE64),
    (HASHICORP_PRECISE32, HASHICORP_PRECISE32)
]
