# software-properties-common and python-software-properties (put both in case, should do more tests)
# for getting add-apt-repository command to work in ubuntu 12.04 and/or 14.04 (cannot accurately recall now)

$rootScript = <<SCRIPT
  apt-get update -y
  apt-get install -y software-properties-common python-software-properties
  apt-get install -y git build-essential gcc clang make autotools-dev autoconf cmake scons
  apt-get update -y
SCRIPT

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "cpp.box"

  # more cpu and memory
  config.vm.provider "virtualbox" do |v|
    v.memory = 4098
    v.cpus = 2
  end

  # Removes "stdin: is not a tty" annoyance as per
  # https://github.com/SocialGeeks/vagrant-openstack/commit/d3ea0695e64ea2e905a67c1b7e12d794a1a29b97
  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"

  # Shell provisioning
  config.vm.provision "shell", inline: $rootScript

end
