
$rootScript = <<SCRIPT
  cd /home/vagrant
  apt-get update -y
  apt-get install -y software-properties-common python-software-properties
  apt-get install -y git build-essential gcc clang make autotools-dev autoconf cmake scons
  
  apt-get update -y
  apt-get install -y 

SCRIPT

$userScript = <<SCRIPT
  cd /home/vagrant
  git clone https://github.com/ampl/gecode -b master
  cd gecode/
  chmod +x configure
  ./configure
  make
  sudo make install
  
SCRIPT

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "gecode.box"

  # more cpu and memory
  config.vm.provider "virtualbox" do |v|
    v.memory = 4098
    v.cpus = 2
  end

  # Removes "stdin: is not a tty" annoyance as per
  # https://github.com/SocialGeeks/vagrant-openstack/commit/d3ea0695e64ea2e905a67c1b7e12d794a1a29b97
  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"

  # Shell provisioning
  config.vm.provision "shell", inline: $rootScript
  config.vm.provision "shell", inline: $userScript

end
